
networks:
  reverse-proxy:
    external: true
    name: ${PROXY_NETWORK:-traefik}

services:
  webserver:
    image: tailormap-embed-nginx:latest
    build:
      context: .
    restart: unless-stopped
    environment:
      - "TZ=Europe/Amsterdam"
      - "EMBED_SRC=${EMBED_SRC:-https://snapshot.tailormap.nl/#!embed:1}"
    networks:
      - reverse-proxy
    labels:
      - "traefik.http.services.${COMPOSE_PROJECT_NAME}.loadbalancer.server.port=80"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.rule=Host(${HOST:-`embed.tailormap.nl`, `embed.tailormap.com`})"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.tls=true"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.tls.certresolver=letsencrypt"
      - "traefik.docker.network=${PROXY_NETWORK:-traefik}"
      - "traefik.enable=true"
