name: Trivy Security Scan
on:
  # use pull request so this workflow dos not fail when triggered by dependabot PR's
  pull_request:
  schedule:
    - cron: '17 23 * * MON'
  workflow_dispatch:

jobs:
  build:
    name: Trivy Scan
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - uses: 'actions/checkout@v4'

      - name: Build images
        run: |
          docker buildx build --pull --build-arg VERSION=snapshot --build-arg BASE_HREF=/ -t ghcr.io/b3partners/tailormap:snapshot . --load

      - name: Run Trivy vulnerability scanner on tailormap-viewer
        uses: 'aquasecurity/trivy-action@0.19.0'
        # docker run --rm -v trivy_cache:/root/.cache/ aquasec/trivy image ghcr.io/b3partners/tailormap:snapshot
        with:
          image-ref: 'ghcr.io/b3partners/tailormap:snapshot'
          format: 'sarif'
          output: 'tailormap-trivy-results.sarif'
          severity: 'HIGH,CRITICAL'

      - name: Upload tailormap-viewer Trivy scan results to GitHub Security tab
        uses: 'github/codeql-action/upload-sarif@v3'
        if: always()
        with:
          sarif_file: 'tailormap-trivy-results.sarif'
          category: 'tailormap'
