name: Validate PR Branch

on:
  pull_request:
    branches:
      - main

jobs:
  check-base-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check if PR is from 'dev' to 'main' or 'main'(original repo) to 'main'(forked repo)
        run: |
          if [[ "$GITHUB_HEAD_REF" != "dev" && "$GITHUB_HEAD_REF" != "main" ]]; then
            echo "Error: Pull requests to 'main' must be from the 'dev' or 'main' branch."
            exit 1
          fi
